### PR TITLE
Docker file with pm2 process manager integrated with express

### PR DESCRIPTION
**Pull request by nimahkh**
- using node :12.13
- installing pm2-runtime 
- adding .circleci with build phase

### CODE REVIEW

**Comment by wellyshen** [comment]
@nimahkh Thank you for this PR, we already have existed [Dockerfile](https://github.com/wellyshen/react-cool-starter/blob/docker/Dockerfile) and [Travis-CI](https://github.com/wellyshen/react-cool-starter/blob/master/.travis.yml) would you help to integrate the PM2 with them instead of creating a new CI service.

**Comment by nimahkh** [comment]
> @nimahkh Thank you for this PR, we already have existed [Dockerfile](https://github.com/wellyshen/react-cool-starter/blob/docker/Dockerfile) and [Travis-CI](https://github.com/wellyshen/react-cool-starter/blob/master/.travis.yml) would you help to integrate the PM2 with them instead of creating a new CI pipeline?

Yes of course. I did something with pm2-runtime on Docker. but I can merge the scripts run commands with PM2 outside of Docker. I will start this. 
Why you dont put Docker on Master branch?

**Comment by wellyshen** [comment]
@nimahkh It's OK to rum PM2 in the Docker. Yes we can integrate the Docker into master, for it do you think we should also add the [commnads](https://github.com/wellyshen/react-cool-starter/blob/docker/package.json#L57)? If we can integrate Docker with PM2 + Travis-CI together, it'll be great :)

**Comment by nimahkh** [comment]
> @nimahkh It's OK to rum PM2 in the Docker. Yes we can integrate the Docker into master, for it do you think we should also add the [commnads](https://github.com/wellyshen/react-cool-starter/blob/docker/package.json#L57)? If we can integrate Docker with PM2 + Travis-CI together, it'll be great :)

Yes. it is ideal. I will do it. now it is integrated with Docker in the PR. I will do it in Travis too.

**Comment by wellyshen** [comment]
@nimahkh Thank you. Base on your Docker configuration, what kind of script command do you think we need for the master branch?

**Comment by nimahkh** [comment]
> @nimahkh Thank you. Base on your Docker configuration, what kind of script command do you think we need for the master branch?

`"pm2" : "pm2-runtime start npm --start"`

Then we can change the Docker command to : `yarn pm2`

**Comment by wellyshen** [comment]
@nimahkh What I think is to isolate the Docker part by install PM2 and execute the app in it. From a view of developer. How do you think about it?

BTW, do we need to migrate [these](https://github.com/wellyshen/react-cool-starter/blob/docker/package.json#L57) docker commands into master? How's ur suggestion?

**Comment by nimahkh** [comment]
> @nimahkh I think it’s OK to install PM2 from Docker. By doing this developers don’t need to install PM2 package from app project. How do you think about it?

Of course. it is what I did in PR.

**Comment by amerllica** [comment]
@wellyshen, Based on your words, in one of [my rejected PR](https://github.com/wellyshen/react-cool-starter/pull/255#issuecomment-546859195), this is a cool starter and because of the simplicity you rejected to having `.env` here.

But, now we have a fully-featured starter and now I see we have complete DevOps features, but still for having basic configs we use some configuration files. in your opinion is that time to have the basic configuration like API_URL in the system environment variables?

**Comment by wellyshen** [comment]
@amerllica It's good to have a better environment configuration for most users, who using this starter. I need time to survey some related tools or best practice first, but there're some ideas in we should keep in mind:

- Centralized configurations in a file (if possible).
- As simple as possible, minimal configurations is fine.
- Related documentation.

**Comment by wellyshen** [comment]
Close it due to the existing [docker branch](https://github.com/wellyshen/react-cool-starter/tree/docker).

**Pull request closed without merging**
