### PR TITLE
Simplified using of starter

### PR DESCRIPTION
**Pull request by alirezavalizade**
Thanks again for this cool starter, I have some experience with it in big scale projects, 
The first issue is in actions because for simple fetching we should write a lot of code.
The Second one is not needed to call another action to check we should call api or not.
So, I have these changes:
* create a simple middleware in configureStore.js 
I added Promise base middleware and i comment it because i want know your opinion about this.(If you ok please say to uncomment it)
I added Async base middleware(But i recommend use from Promise in our middleware because we can access to data and error straightly in our component from that action).
* change actions usage
* we should remove redux-thunk library because we don't need it any more

### CODE REVIEW

**Comment by wellyshen** [comment]
@alirezavalizade,

I'm very appreciate you for this idea. I have spent time to think about it. That I prefer to keep action creator flexible. The middleware indeed simplified the API calling. But there're some other use cases might need to involve redux store in action creator. For example, I'm using the **firestore** of **Firebase** which isn't fetch by `axios` and I need to get the status from my reducer to decide the next step etc.

BTW, why we don't need to prevent user from calling action repeatedly on SSR? Just curious about your opinion.

**Comment by alirezavalizade** [comment]
I'm with you on this, But for me speed up in development is very important. We are using this starter for develop our projects and time is also very important for us, create several actions step by step with this way can waste the time! we can publish this feature on another branch for use.

**Comment by wellyshen** [comment]
@alirezavalizade OK, good idea.

**Comment by alirezavalizade** [comment]
@wellyshen 
Thank you, I'm going to send pull requests for cleaning up and update it in next days.

**Comment by wellyshen** [comment]
@alirezavalizade I list the branch [here](https://github.com/wellyshen/react-cool-starter#some-feature-branches).

**Comment by alirezavalizade** [comment]
Perfect @wellyshen

**Comment by wellyshen** [comment]
@alirezavalizade I need someone help me for fixing the unit testing for the branch. If you're interesting about it. I can invite you as the co-worker. How do you think about it?

**Comment by alirezavalizade** [comment]
@wellyshen It's ok i'm interested, I can help you.

**Comment by wellyshen** [comment]
@alirezavalizade Great! I sent the invitation to you.

**Pull request merged**
