### PR TITLE
upgrade to react fiber because why not

### PR DESCRIPTION
**Pull request by tagraha**

### CODE REVIEW

**Comment by iamacup** [comment]
I am a bit confused by this PR - I can’t find out what the 'next' package version does in Yarn? Which version of the [React](https://github.com/facebook/react/blob/master/CHANGELOG.md) changelog does this update to?

Sorry if it is just me being confused :)

edit: answered it here almost immediately: https://github.com/facebook/react/issues/10294, apologies. 

I wonder if the repo should use an RC or wait for 16.0 to be finalized? As a boilerplate for real world apps i would be slightly cautious.

**Comment by wellyshen** [comment]
Hi @tagraha Thank you for telling about it. My concern is the "next" version of react and react-dom might conflicts or have bugs with other dependencies. Therefore I prefer define a specific react and react-dom version for this project.

**Comment by tagraha** [comment]
time to upgrade now? https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

**Comment by iamacup** [comment]
yep :) - PR will need change though ?

 react                ^15.6.1  →  ^16.0.0 
 react-dom            ^15.6.1  →  ^16.0.0 
 react-test-renderer  ^15.6.1  →  ^16.0.0

**Comment by wellyshen** [comment]
I'm doing this

**Comment by iamacup** [comment]
@wellyshen cool thanks :)

looks like there will need to be a couple of code changes as well for this:

Calling ReactDOM.render() to hydrate server-rendered markup will stop working in React v17. Replace the ReactDOM.render() call with ReactDOM.hydrate() if you want React to attach to the server HTML.

**Comment by wellyshen** [comment]
Done

**Pull request closed without merging**
