### PR TITLE
remove loadData and use from componentWillMount life cycle for prefetch data

### PR DESCRIPTION
**Pull request by alirezavalizade**
@wellyshen i found a way to remove loadData in routes and can dispatch actions in componentWillMount for prefetching data. But i'm going to push again on this `pull-request`.
Please check these change, if was a good solution i can add this feature to master branch.
We needn't to call actions in loadData or import them in routes file, I think it's so much cleaner.

This screen shot can showing that prefetching is working correctly.

screen shot 2018-03-01 at 1 01 12 pm

### CODE REVIEW

**Comment by wellyshen** [comment]
@alirezavalizade Call API in `componentWillMount` seems [not a properly way](https://daveceddia.com/where-fetch-data-componentwillmount-vs-componentdidmount/), how do you think about it?

**Comment by alirezavalizade** [comment]
@wellyshen why?
It's just a life cycle that we can use it on server...

**Comment by wellyshen** [comment]
OK, let's merge it to the `simple-action` branch. I will spend time to test it and think about. It's a big change man ;) 

There're some things we can do will for maintaining this starter:
* Keep file name consistent, e.g. seems the server reducer name is different from others.
* Keep dependencies on the trend (BTW, I'll drive the webpack v4 dependency upgrade).
* Eliminate flow type error.
* Update related README tutorials section.

**Comment by alirezavalizade** [comment]
@wellyshen Thank you, yes i'll fix these issues...
what about renaming actions and reducers? I noticed that you are naming reducers according to the related container, but i think it has issue on big scale projects, we should naming actions and reducers according to our name space api that we use, I mean if we are using `/users/` api, we should create a reducer that file name is `users.reducer.js`, and a `users.action.js` as well, please think about this suggestion and tell me what's your opinion?
I wanted to do these changes and tell you my suggestion and it was reason of my bad naming in this pull request, sorry.

**Comment by wellyshen** [comment]
@alirezavalizade Sounds reasonable. I think the definition of the `simple-action` branch is for advanced developers. I will be busying for my working recently so if you have any  great idea for this branch just push it directly without PR. I'll spend time to review and learn something from the branch 👍

**Pull request merged**
