### PR TITLE
Having faster development area for babel.

### LINKED ISSUE #610: Having faster development area for babel.
Duo to enhancement, we should stop compacting babel on the development mode. so I should add a little config to the babel configuration file.

### PR DESCRIPTION
**Pull request by amerllica**
I set some babel configurations based on [babel docs](https://babeljs.io/docs/en/options) and this PR will resolve #610

### CODE REVIEW

**Comment by wellyshen** [comment]
@amerllica I think the default values are fine, do we really need to set these configurations manually?

**Comment by amerllica** [comment]
@wellyshen, I read the docs on [`babeljs.io/options`](https://babeljs.io/docs/en/options) and unfortunately, the default configurations are not optimized. please read the mentioned link.

**Comment by wellyshen** [comment]
@amerllica 

- For the necessary side: I'm curious how faster with these configurations.
- For total solution side: They're many [options](https://babeljs.io/docs/en/babel-generator#options) why you pick up the three? Any reference for optimizing the DX with babel options?

**Comment by amerllica** [comment]
@wellyshen 

- I believe `compact: false` is very better than the default (`compact: 'auto'`), because I'm sure that in the development mode no compact happens. Also, I don't know about the speed of this configuration, and it is not measurable. because in the first of starting an app it seems it has no difference. but when the app became large with many several modules and components, developers can sense the difference. this starter is luxe and awesome, why should not has micro-optimization for both _development_ and _production_ side?

- This question is a little weird, I think you are seeking a reason to reject this PR, there are many options, I faced some of them and wanna improve just these little things. there is no promise that a contributor should read all options and optimize all of them. good things happen step by step. some steps pass by me some by others and in the end a mature product will happen.

**Comment by wellyshen** [comment]
@amerllica 

I think your starting point is good but the positioning of this library is "a starter". So, every time I adding a new feature, I asking myself "does everyone need it?", what's the best practice for it? If not everyone need it, I think we should keep the decision to users.

BTW, I might not fully understand about it, I'll spend time to survey and study it.

**Comment by wellyshen** [comment]
Close due to the idea of simple and clear of this start-kit.

**Pull request closed without merging**
