### PR TITLE
Remove __CLIENT__ and __SERVER__ globals

### PR DESCRIPTION
**Pull request by iamacup**
Up to you if you want this PR,

The `__CLIENT__` and `__SERVER__` are not currently used in the code base, and really, we should avoid their use in the future.

React provides methods that are server / client only.

### CODE REVIEW

**Comment by iamacup** [comment]
This also fixes https://github.com/wellyshen/react-cool-starter/issues/108 but i had to restructure the way the constructor is called because the linter wants the comma there otherwise.

**Review by aagentah — APPROVED** [review]

**Comment by wellyshen** [comment]
@iamacup Yea, I know. But speaking out of react. Don't we need to keep it for someone who wnat to differentiate their code functions or something between client / server?

**Comment by iamacup** [comment]
@wellyshen its totally up to you - my preference is to avoid this kind of logic - but i understand why the boilerplate might want it - up to you :)

Can you commit something that fixes https://github.com/wellyshen/react-cool-starter/issues/108, https://github.com/wellyshen/react-cool-starter/issues/112 and https://github.com/wellyshen/react-cool-starter/issues/114 if you don't do this pull :) 

Cheers

**Comment by wellyshen** [comment]
@iamacup 
Thank you for asking these issues. I have fixed the error of `./index.js`.
These issues are occurs due to the code style of Airbnb, but not the global variables.
Ask we discussed, keep the global variables for developers who want to do something different between server-side and client-side.

**Pull request closed without merging**
