### PR TITLE
Migrate from react-loadable to loadable-component

### PR DESCRIPTION
**Pull request by xD3CODER**
Library Loadable-component is recommended as the best alternative of Lazy for SSR. 
React-loadable is not maintained for a while.

### CODE REVIEW

**Comment by Rid** [comment]
LGTM, we should remove `ErrorDisplay` and replace with an `ErrorBoundary` component to catch loading errors.

I can add it or you can do it in this PR?

**Comment by xD3CODER** [comment]
I let you add it, I've never used errror boundaries

**Comment by Rid** [comment]
@xD3CODER I've made a PR on your fork, so we can get it into this PR

**Comment by Rid** [comment]
@wellyshen I think this is ready to be merged

**Review by Rid — APPROVED** [review]

**Comment by wellyshen** [comment]
@xD3CODER @Rid Thank you both I will spend time to review this PR. 💯

**Comment by wellyshen** [comment]
@xD3CODER @Rid Thank you both, everything looks great 👍

**Comment by wellyshen** [comment]
@all-contributors please add @xD3CODER  for code

**Comment by wellyshen** [comment]
@all-contributors please add @Rid  for code

**Pull request merged**
