### PR TITLE
material-ui: Added Material-UI with SSR

### PR DESCRIPTION
**Pull request by RomanBON**

### CODE REVIEW

**Comment by wisekaa03** [comment]
This is what I waiting for... 👍

**Comment by wellyshen** [comment]
@RomanBON Thank you for your hard work. As a start kit I think it's better to let user choice their favorite theme. How do you think about it?

**Comment by RomanBON** [comment]
@wellyshen Thank you for your boilerplate! Сustomizing the Material-UI is not always easy, so I think that it would be possible to accept pull request in a new branch, if you do not mind)))

**Comment by wellyshen** [comment]
@RomanBON I think your idea is workable. One thing I'm concerning is someone need to maintain the new branch. (all dependencies and code follows the main repo ASAP). Can you handle this?

BTW, I'm upgrading this starter to webpack 4. And there're some big changes and if the new branch exist which also need to follow up the new changes.

**Comment by RomanBON** [comment]
@wellyshen Yes, I think I can maintain Material-UI branch ASAP))

**Comment by wellyshen** [comment]
@RomanBON Cool, can you solve the conflicts and push a new PR to the [material-ui](https://github.com/wellyshen/react-cool-starter/tree/material-ui) branch?

**Comment by RomanBON** [comment]
@wellyshen Yes, of course. Thank you!

**Comment by wellyshen** [comment]
@all-contributors please add @RomanBON  for example

**Pull request closed without merging**
