### PR TITLE
Upgrade normalize.css to v8.0.0

### PR DESCRIPTION
**Pull request by forwardomg**
What do you think, maybe we should include this package in the package.json?

### CODE REVIEW

**Comment by wellyshen** [comment]
@forwardomg Thanks man. I use normalize.css as your suggestion, therefore I close this PR 👍

**Comment by forwardomg** [comment]
@wellyshen Alright :)  But this PR includes only update normalize.css to version 8.0.0 without any other changes

**Comment by wellyshen** [comment]
@forwardomg I push a new commit therefore I can't merge this via GitHub. You can send me a new RP if you want ;)

**Comment by forwardomg** [comment]
@wellyshen Oh, I'm sorry, I didn't see that you added my suggestion 👍 Hard day. Thanks.

**Pull request closed without merging**
