### PR TITLE
Dockerfile (s)

### PR DESCRIPTION
**Pull request by jmsherry**
Dockerfile you may wish to change the ports on (80<inner>:<outer>*)); listens on 0.0.0.0
env variable to supress openBrowser
"start:production:docker" as launch task, to allow differentiation
Added a few lines to README.md

### CODE REVIEW

**Comment by wellyshen** [comment]
@jmsherry Why need a duplicated `server.js`?

**Comment by jmsherry** [comment]
@wellyshen I've never done a pull req before, so sorry if I've done something wrong!

The diff between your server.js and mine is that I put an if statement around the openBrowser, because you don't want to open a browser inside a container.

**Comment by wellyshen** [comment]
@jmsherry Your `server.js` path is `./server.js`, why didn't you leverage the `./src/server.js`?

**Comment by jmsherry** [comment]
Yeah, I've done something wrong with the PR. I did use your `./src/server.js`.  I've not created a new file... I'll try and figure out how to do it. :(

I used the drag/drop files - I think that's the problem.

**Comment by wellyshen** [comment]
@jmsherry
OK, I see.
If the docker part can be tested by travis CI? I want to make sure it works fine if I upgrade dependencies or do some code refinement etc. in the future.

BTW, free feel to close this PR and send me a new one when you adjusting the location of the server.js file.

**Comment by jmsherry** [comment]
Sure. I'm working on a crazy project atm, so I'll get to it as soon as I can...

Docker doesn't work like that. Docker is basically a shell level daemon. It's like a VM. With Travis you can build container; launch it and then [SSH into it to run tests](https://docs.travis-ci.com/user/docker/), but you don't test it itself.

I'll close the PR and try and make another one ASAP.

**Comment by wellyshen** [comment]
@all-contributors please add @jmsherry  for infra

**Pull request closed without merging**
