### PR TITLE
replace `loadable-content` with `react-loadable`

### LINKED ISSUE #197: Loadable-component doesn't have any stratgies for prefetching
### Do you want to report a bug or request a feature?
React cool starter uses `loadable-components` which [doesn't support prefetch of chunks](https://github.com/smooth-code/loadable-components/issues/77) in `SSR` and there is no future target towrad it.

### Expected Behavior
Replacing package with `react-loadable` would be beneficiary

### Actual Behavior
In `SSR` page rendering takes place with out any related styles which results in FOUC.

### PR DESCRIPTION
**Pull request by MortezaT**
fixes #197

### CODE REVIEW

**Comment by wellyshen** [comment]
@MortezaT Thank you for this PR. There're some async [components](https://github.com/wellyshen/react-cool-starter/blob/master/src/pages/index.js) seems not be replaced by `react-loadable`

**Comment by MortezaT** [comment]
@wellyshen 
There is no need for any further changes.
everything works just alright.

**Comment by wellyshen** [comment]
@MortezaT Thank you for doing this change. I'm reviewing this PR. I found there's an error from the console log of Google Chrome as following. Can you help to fix it?

**Comment by MortezaT** [comment]
@wellyshen that's a [react 16 issue](https://github.com/facebook/react/issues/10879) which interprets white spaces as difference between `SSR` (which is not minified in `development`) and `client.js` (chunked and minified).

If you run it in `production` you'll see no errors.

**Comment by wellyshen** [comment]
@MortezaT Thank you for sharing this issue. I remember that I didn't choice `react-loadable` was because I can't solve this issue at that time. So I choose `loadable-component` instead but the downside is it doesn't support style in SSR. For better developing experience I still wish we can get ride of this error in development. I will spend time to find the solution. as soon as I solve the error. I'll merge this PR. Thank you for your hard working 👍

**Comment by Rid** [comment]
@wellyshen @MortezaT I'm looking into this error, here seems to be the chronology of the error:

1. The html is rendered on the server with the full User List sent to the browser
2. Once the client has loaded it then begins to load the components for the route

So after 1. the DOM contains the User List `<div>`, however at the start of 2. no components are loaded so the `<div>` containing the User List is no longer there, hence the error.

I'm not familiar enough with react-loadable yet to understand if this is normal behaviour, I can't understand how the server and client DOM will match if the component needs to be loaded in the client before displaying the data (as this will always require a Loading... `<div>` whereas the server has pre-rendered with the component already loaded).

I'll continue investigating and update you later.

**Comment by wellyshen** [comment]
@Rid Thank you for your time.

**Comment by wellyshen** [comment]
@all-contributors please add @MortezaT for code

**Pull request merged**
