### PR TITLE
Omit map files from production build

### LINKED ISSUE #247: No map file for production level
### No map file needed for production level (feature)

- For the production level, there is no need to have `map` files because downloading and parsing and mapping them have a large cost for clients browsers, especially for mobile devices.

### Expected Behavior

For production, the project shouldn't generate `map` files for JavaScript and CSS bundles. this awesome starter should be very light in production running.

### Actual Behavior

All map files are generated for the `yarn build` command.

### Your Environment

- Client OS: all
- Browser and its version: all
- Version of node: all

### PR DESCRIPTION
**Pull request by amerllica**
The `PR` will close #247 issue after accepting.

### CODE REVIEW

**Comment by wellyshen** [comment]
@amerllica I think map files already omitted in production by the `isDev` variable. If you set them as `true` that we won't omit them in production right?

**Comment by wellyshen** [comment]
@amerllica We already omitted the source map of css. So I close this PR. If I misunderstand something please let me know.

**Comment by amerllica** [comment]
Dear @wellyshen, when a developer run `yarn build` command in the `public` folder all CSS and JS bundles are saw, and also the map files for them are created, these map files are not necessary for production level.

It's so obvious, clone from git and just run `yarn build` then you see it. you never omit map files from production.

**Comment by wellyshen** [comment]
@amerllica We did omit the `.css` map but not `.js`. And I'll release a new version to omit the `.js` map (by assigning `false` to [devtool](https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js#L94) in production) later. Thank you for let me know about it.

**Pull request closed without merging**
